site_name: Wiren Board Docs
site_url: https://aadegtytarev.github.io/mkdocs-test
nav:
    - Home: index.md
    - Контроллеры:
        - Wiren Board 7: plc/wb7/index.md
        - Wiren Board 6: plc/wb6/index.md
    - Реле:
        - WB-MR6C v.2: relay/wb-mr6c-v2/index.md

theme: material

theme:
  features:
    - content.tabs.link

plugins:
  - include-markdown

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
