site_name: Wiren Board Docs
site_url: https://aadegtytarev.github.io/mkdocs-test
nav:
    - Home: index.md
    - Контроллеры:
        - Wiren Board 7: plc/wb7/index.md
        - Wiren Board 6: plc/wb6/index.md
    - Реле:
        - WB-MR6C v.2: relay/wb-mr6c-v2/index.md
    - Софт:
        - wb-mqtt-serial: git/includes/wb-mqtt-serial.md

theme: 
  name: material
  features:
    - content.tabs.link
    - content.action.edit
  language: ru

plugins:
  - include-markdown
  - glightbox
  - external-markdown
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ['.','../includes','docs/']
      check_paths: true
      url_download: true
  - toc:
      permalink: true

repo_url: https://github.com/aadegtyarev/mkdocs-test
edit_uri: edit/main/docs/
