site_name: Wiren Board Docs
site_url: https://aadegtytarev.github.io/mkdocs-test
nav:
    - Home: index.md
    - Софт:
        - soft/index.md
        - wb-mqtt-homeui: soft/wb-mqtt-homeui/index.md
        - wb-mqtt-serial: soft/wb-mqtt-serial/index.md
        - wb-rules: soft/wb-rules/index.md
theme: 
  name: readthedocs
  language: ru
  primary: green

plugins:
  - search

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/aadegtyarev/mkdocs-test
