site_name: Wiren Board Docs
site_url: https://aadegtytarev.github.io/mkdocs-test
nav:
    - Home: index.md
    - Контроллеры:
        - plc/index.md
    - Реле:
        - relay/index.md
    - Софт:
        - soft/index.md

theme: 
  name: material
  features:
    - content.tabs.link
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - toc.integrate
  language: ru
  primary: green

plugins:
  - include-markdown
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-video
  - table-reader
  - external-markdown

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: 3

repo_url: https://github.com/aadegtyarev/mkdocs-test
edit_uri: edit/main/docs/
