site_name: Wiren Board Docs
site_url: https://aadegtytarev.github.io/mkdocs-test
nav:
    - Home: index.md
    - Контроллеры:
        - Wiren Board 7: wb7/index.md
        - Wiren Board 6: wb6/index.md
    - Реле:
        - WB-MR6C v.2: wb-mr6c-v2/index.md

theme: material
